### PR TITLE
Update regex to avoid /e depreciation

### PR DESCRIPTION
**Pull request by felipeumpierre**
Update the regex line to avoid the notice message:

_The /e modifier is deprecated, use preg_replace_callback_

php version: 5.6.13

### CODE REVIEW

**Comment by miladrahimi** [comment]
Thanks for checking, yes, it seems, that's gonna be not supported soon, but the solution is not what is pulled, It need to be changed to `preg_replace_callback()`. I will fix it as soon as possible.

**Comment by felipeumpierre** [comment]
I updated my commit changing the `pre_replace` to `preg_replace_callback`.

**Comment by felipeumpierre** [comment]
@miladrahimi ping

**Comment by miladrahimi** [comment]
Done! Thanks for your forking dude.

**Pull request merged**
